name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pint:
    runs-on: ubuntu-latest
    name: Pint
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Fix code style
        run: composer lint

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style: apply pint fixes'

  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Run static analysis
        run: composer analyse
